### ISSUE TITLE
MKR 1010 Getting a -2 Return Code 

### ISSUE THREAD

**Issue by jpagliaccio** [firedog1024/mkr1000-iotc#1] opened 2019-01-12 04:46 UTC
Hey FD: Nice work. I am trying to get your code running on a MKR 1010. I have everything configured, but I cant find the Scope ID in my IoT Hub. Central has been depreciated. I tried commenting out scope ID and I get a "---> mqtt failed, rc=-2" when it sends. Any Ideas?

**Comment by firedog1024** [comment] 2019-01-14 19:19
The code was designed to work against Azure IoT Central (https://azure.microsoft.com/en-us/services/iot-central/).  The ScopeID is specific to IoT Central as we use the Device Provisioning Service to get the IoT Hub to connect to.  To make this work with a regular Azure IoT Hub you will need to change the code so it works like a MKR1000 (due to technical issues we cannot get this device to work with DPS yet so it drops back to a connection string).  Look at the code in mkr10x0_iotc.ino and change line 25 to be mkr_devices mkrdevice = MKR1000;  Then paste in the device connection string into line 5 of configure.h and you should be good to go!

**Comment by jpagliaccio** [comment] 2019-01-15 16:33
Hey FD: Thanks. That worked. I get: 

Sending telemetry ...
	{"temp":   62.12, "humidity":   67.22}
--> IoT Hub acknowledges successful receipt of twin property: 2

I am going to try to understand your code a little better and pull out some of the Central code. I am preparing for the MKR 1500 when it starts to ship.

Thanks again.

**Comment by firedog1024** [comment] 2019-01-16 22:46
Excellent, glad I could help you out.  Yes you can pull out the code specific to IoT Central and reduce the firmware size.  We're also excited for the MKR1500 as it opens up low power communication to Azure IoT.  If you run into any other problems feel free to ping me and I'll try and help out.  For now I'm going to close this issue.

**Closed as completed by firedog1024** 2019-01-16 22:46 UTC
